# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "H3eftmIcH5csp/ba968PJrVWuE2TxcdQ1cfzFTFT4zRMZwMZj+dqzeJ/aimeAHHggCTLOCYlqT0ZYSitlO1ey6oQBxhn3pSlx76KeXkJjdCizWJ0U+0BLMw497su9PmJHh0Wu4dNUr/lseYBk7+WFa0o/jZONoUmiOINan4dxMUBEHT+PPUxMp4q5b4ltWmInDaiCdRYetLQI8vPDfIpWOLITYUMttMRVbTvXB5JL9gCasxE6iW1q5jw+W5UpT09SQI4VZ/acX2nZm37t1+n8JPOWdZ7bHBv9V3KUUiJYX6W8mK9n9KvIs7XRHHpwRiJtWBtLkGx8dEpkBw+7wJB8nEbH0DnpgMlNjTao79XbK0eil6FJvo2PltIVbxPFY/GenG4C50g4x0t4R9+bTo1va/hJ030ujADsTMYRkT0IResWp7KgwKi555YZXIyEJnIAaTFjKxFbGYStc31W9jY2JRvOipsvnsx40wCDmRJ5wGZjJuWhzc0rEso3CW4POtAFYeb1TShoUWCUWrGo1Ag9OyfPqt4Mc/ZLnvbPT5t/Wngj7rOEnCNOCRlGUBxCc7taWi+KFvqtaRY6Akp8m5YPbHY60XngkkGw1Vc8A7vk1myWrPSba0z5o+KcmZu2X/8o/8TiePKQHsp/x/LN/K8rjVUR5YXg6H1umv455MLi1Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
