travis:
  secure:
    BINSTAR_TOKEN: H3eftmIcH5csp/ba968PJrVWuE2TxcdQ1cfzFTFT4zRMZwMZj+dqzeJ/aimeAHHggCTLOCYlqT0ZYSitlO1ey6oQBxhn3pSlx76KeXkJjdCizWJ0U+0BLMw497su9PmJHh0Wu4dNUr/lseYBk7+WFa0o/jZONoUmiOINan4dxMUBEHT+PPUxMp4q5b4ltWmInDaiCdRYetLQI8vPDfIpWOLITYUMttMRVbTvXB5JL9gCasxE6iW1q5jw+W5UpT09SQI4VZ/acX2nZm37t1+n8JPOWdZ7bHBv9V3KUUiJYX6W8mK9n9KvIs7XRHHpwRiJtWBtLkGx8dEpkBw+7wJB8nEbH0DnpgMlNjTao79XbK0eil6FJvo2PltIVbxPFY/GenG4C50g4x0t4R9+bTo1va/hJ030ujADsTMYRkT0IResWp7KgwKi555YZXIyEJnIAaTFjKxFbGYStc31W9jY2JRvOipsvnsx40wCDmRJ5wGZjJuWhzc0rEso3CW4POtAFYeb1TShoUWCUWrGo1Ag9OyfPqt4Mc/ZLnvbPT5t/Wngj7rOEnCNOCRlGUBxCc7taWi+KFvqtaRY6Akp8m5YPbHY60XngkkGw1Vc8A7vk1myWrPSba0z5o+KcmZu2X/8o/8TiePKQHsp/x/LN/K8rjVUR5YXg6H1umv455MLi1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
